export const CARD_ICONS = {
  code_vibes: [
    "angular.svg",
    "bootstrap.svg",
    "css.svg",
    "django.svg",
    "firebase.svg",
    "git.svg",
    "github.svg",
    "html.svg",
    "js.svg",
    "node-js.svg",
    "python.svg",
    "react.svg",
    "sass.svg",
    "sql.svg",
    "terminal.svg",
    "ts.svg",
    "vs-code.svg",
    "vue-js.svg",
  ],

  gaming: [
    "banana.svg",
    "card.svg",
    "coin.svg",
    "cone-circle.svg",
    "controller.svg",
    "creeper.svg",
    "cubes.png",
    "gameboy.svg",
    "labyrinth.svg",
    "level-up.svg",
    "cone-square.svg",
    "pacman-yellow.svg",
    "pacman.svg",
    "play-btn.svg",
    "puzzle.svg",
    "snake.svg",
    "cone-triangle.svg",
    "toad.svg",
  ],
};

export const CARD_ICONS_ALT_TEXTS = {
  code_vibes: [
    "Angular Icon",
    "Bootstrap Icon",
    "CSS Icon",
    "Django Icon",
    "Firebase Icon",
    "Git Icon",
    "GitHub Icon",
    "HTML Icon",
    "JavaScript Icon",
    "Node.js Icon",
    "Python Icon",
    "React Icon",
    "Sass Icon",
    "SQL Icon",
    "Terminal Icon",
    "TypeScript Icon",
    "VS Code Icon",
    "Vue.js Icon",
  ],
  gaming: [
    "Banana Icon",
    "Card Icon",
    "Coin Icon",
    "Cone Circle Icon",
    "Controller Icon",
    "Creeper Icon",
    "Cubes Icon",
    "Gameboy Icon",
    "Labyrinth Icon",
    "Level Up Icon",
    "Cone Square Icon",
    "Yellow Pacman Icon",
    "Pacman Icon",
    "Play Button Icon",
    "Puzzle Icon",
    "Snake Icon",
    "Cone Triangle Icon",
    "Toad Icon",
  ],
};
