// type GamingIcon =
//   | "banana"
//   | "card"
//   | "coin"
//   | "cone-circle"
//   | "controller"
//   | "creeper"
//   | "cubes"
//   | "gameboy"
//   | "labyrinth"
//   | "level-up"
//   | "cone-square"
//   | "pacman-yellow"
//   | "pacman"
//   | "play-btn"
//   | "puzzle"
//   | "snake"
//   | "cone-triangle"
//   | "toad";

// type CodeVibesIcon =
//   | "angular"
//   | "bootstrap"
//   | "css"
//   | "django"
//   | "firebase"
//   | "git"
//   | "github"
//   | "html"
//   | "js"
//   | "node-js"
//   | "python"
//   | "react"
//   | "sass"
//   | "sql"
//   | "terminal"
//   | "ts"
//   | "vs-code"
//   | "vue-js";

// export type IconName = GamingIcon | CodeVibesIcon;
